#!/bin/bash
# This script: is used create a input test file and verify outputs

#   Create random input test file. Generate expected output files
python test/tweets_test.py

#   Run the original solution on random input test file created above. Generate output files in the same folder
python src/analyze_tweets.py test/tweets_random.txt test/ft1_result.txt test/ft2_result.txt

#   Compare output files generated by above two python programs
diff test/ft1_result.txt test/ft1_expected.txt
diff test/ft2_result.txt test/ft2_expected.txt
